# Generated by Django 4.2.9 on 2025-09-07 05:51

import apps.audio_processing.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Reunión',
                'verbose_name_plural': 'Tipos de Reunión',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProcesamientoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del proceso', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del proceso')),
                ('archivo_audio', models.FileField(help_text='Archivo de audio original', upload_to=apps.audio_processing.models.audio_upload_path)),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='Duración en segundos', null=True)),
                ('formato', models.CharField(blank=True, max_length=10)),
                ('tamano_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('transcribiendo', 'Transcribiendo'), ('diarizando', 'Diarizando'), ('completado', 'Completado'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('progreso', models.PositiveSmallIntegerField(default=0, help_text='Progreso en porcentaje')),
                ('mensaje_estado', models.TextField(blank=True, help_text='Mensaje detallado del estado actual')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_reunion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audio_processing.tiporeunion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesamientos_audio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procesamiento de Audio',
                'verbose_name_plural': 'Procesamientos de Audio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=10)),
                ('mensaje', models.TextField()),
                ('detalles_json', models.JSONField(blank=True, null=True)),
                ('procesamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='audio_processing.procesamientoaudio')),
            ],
            options={
                'verbose_name': 'Log de Procesamiento',
                'verbose_name_plural': 'Logs de Procesamiento',
                'ordering': ['-timestamp'],
            },
        ),
    ]
