# Generated by Django 4.2.9 on 2025-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamientoaudio',
            name='archivo_mejorado',
            field=models.FileField(blank=True, help_text='Archivo de audio procesado y mejorado', null=True, upload_to='audio/mejorado/'),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='confidencial',
            field=models.BooleanField(default=False, help_text='Proceso confidencial'),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='duracion_seg',
            field=models.FloatField(blank=True, help_text='Duración exacta en segundos (decimal)', null=True),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='etiquetas',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=200),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='metadatos_procesamiento',
            field=models.JSONField(blank=True, default=dict, help_text='Metadatos del pipeline de procesamiento'),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='sample_rate',
            field=models.IntegerField(blank=True, help_text='Frecuencia de muestreo', null=True),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='version_pipeline',
            field=models.CharField(default='v2.0', help_text='Versión del pipeline de procesamiento', max_length=20),
        ),
    ]
