# Generated by Django 4.2.9 on 2025-09-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0002_procesamientoaudio_archivo_mejorado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamientoaudio',
            name='participantes',
            field=models.TextField(blank=True, help_text='Lista de participantes'),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación donde se realizó la reunión', max_length=200),
        ),
    ]
