# Generated by Django 4.2.9 on 2025-09-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0003_procesamientoaudio_participantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamientoaudio',
            name='bit_rate',
            field=models.IntegerField(blank=True, help_text='Bit rate del audio', null=True),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='canales',
            field=models.IntegerField(blank=True, help_text='Número de canales de audio', null=True),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='codec',
            field=models.CharField(blank=True, help_text='Codec utilizado', max_length=50),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='metadatos_originales',
            field=models.JSONField(blank=True, default=dict, help_text='Metadatos completos del archivo original'),
        ),
        migrations.AddField(
            model_name='procesamientoaudio',
            name='participantes_detallados',
            field=models.JSONField(blank=True, default=list, help_text='Lista detallada de participantes con nombre, apellido, cargo, institución y orden'),
        ),
        migrations.AlterField(
            model_name='procesamientoaudio',
            name='participantes',
            field=models.TextField(blank=True, help_text='Lista de participantes (texto libre para compatibilidad)'),
        ),
    ]
