# Generated by Django 4.2.9 on 2025-09-28 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generador_actas', '0008_delete_promptlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_header_enabled', models.BooleanField(default=True)),
                ('pdf_footer_enabled', models.BooleanField(default=True)),
                ('pdf_watermark', models.CharField(blank=True, max_length=200)),
                ('pdf_template', models.CharField(choices=[('oficial', 'Plantilla Oficial'), ('simple', 'Plantilla Simple'), ('completa', 'Plantilla Completa')], default='oficial', max_length=100)),
                ('word_template_path', models.CharField(blank=True, max_length=500)),
                ('word_styles_enabled', models.BooleanField(default=True)),
                ('txt_encoding', models.CharField(choices=[('utf-8', 'UTF-8'), ('latin-1', 'Latin-1'), ('ascii', 'ASCII')], default='utf-8', max_length=20)),
                ('txt_line_endings', models.CharField(choices=[('lf', 'LF (Unix)'), ('crlf', 'CRLF (Windows)'), ('cr', 'CR (Mac)')], default='lf', max_length=10)),
                ('incluir_metadatos', models.BooleanField(default=True)),
                ('incluir_firma_digital', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Exportación',
                'verbose_name_plural': 'Configuraciones de Exportación',
                'ordering': ['-activa', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoGestionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal para UI', max_length=7)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('permite_edicion', models.BooleanField(default=True)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('visible_portal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estado de Gestión de Acta',
                'verbose_name_plural': 'Estados de Gestión de Actas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GestionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_editado', models.TextField(help_text='Contenido del acta editado por el usuario')),
                ('contenido_original_backup', models.TextField(blank=True, help_text='Backup del contenido original antes de editar')),
                ('version', models.IntegerField(default=1)),
                ('cambios_realizados', models.JSONField(default=dict, help_text='Log de cambios realizados al acta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_edicion', models.DateTimeField(auto_now=True)),
                ('fecha_enviada_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion_final', models.DateTimeField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales sobre el proceso')),
                ('bloqueada_edicion', models.BooleanField(default=False, help_text='Si está bloqueada la edición (enviada a revisión)')),
                ('acta_generada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestion', to='generador_actas.actagenerada')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_gestion', to='gestion_actas.estadogestionacta')),
                ('usuario_editor', models.ForeignKey(blank=True, help_text='Usuario que editó el acta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_editadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestión de Acta',
                'verbose_name_plural': 'Gestión de Actas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, help_text='Fecha límite para completar la revisión', null=True)),
                ('completado', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('revision_paralela', models.BooleanField(default=True, help_text='Si true: revisión paralela; si false: secuencial')),
                ('requiere_unanimidad', models.BooleanField(default=False, help_text='Si requiere aprobación unánime o por mayoría')),
                ('observaciones', models.TextField(blank=True)),
                ('gestion_acta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proceso_revision', to='gestion_actas.gestionacta')),
                ('iniciado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_revision_iniciados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso de Revisión',
                'verbose_name_plural': 'Procesos de Revisión',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('tipo_cambio', models.CharField(choices=[('edicion_contenido', 'Edición de Contenido'), ('cambio_estado', 'Cambio de Estado'), ('envio_revision', 'Envío a Revisión'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('publicacion', 'Publicación'), ('exportacion', 'Exportación')], max_length=50)),
                ('descripcion', models.TextField()),
                ('datos_adicionales', models.JSONField(default=dict, help_text='Datos adicionales sobre el cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('gestion_acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='gestion_actas.gestionacta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambios',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='RevisionIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisado', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios del revisor')),
                ('observaciones_tecnicas', models.TextField(blank=True, help_text='Observaciones técnicas sobre el contenido')),
                ('tiempo_revision_minutos', models.IntegerField(blank=True, help_text='Tiempo dedicado a la revisión en minutos', null=True)),
                ('proceso_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='gestion_actas.procesorevision')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisión Individual',
                'verbose_name_plural': 'Revisiones Individuales',
                'ordering': ['fecha_asignacion'],
                'unique_together': {('proceso_revision', 'revisor')},
            },
        ),
    ]
