# Generated by Django 4.2.9 on 2025-09-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionacta',
            name='acta_generada',
        ),
    ]
