# Generated by Django 4.2.9 on 2025-09-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generador_actas', '0008_delete_promptlog'),
        ('gestion_actas', '0002_remove_gestionacta_acta_generada'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionacta',
            name='acta_generada',
            field=models.OneToOneField(blank=True, help_text='Acta generada original de la cual deriva esta gestión', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestion', to='generador_actas.actagenerada'),
        ),
    ]
