# Generated by Django 4.2.9 on 2025-09-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20250906_1518'),
        ('gestion_actas', '0003_gestionacta_acta_generada'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionacta',
            name='acta_portal',
            field=models.OneToOneField(blank=True, help_text='Referencia al acta publicada en el portal ciudadano', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.actamunicipal'),
        ),
    ]
