# Generated by Django 4.2.9 on 2025-09-25 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config_system', '0002_smtp_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPermissionProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código único')),
                ('permission_type', models.CharField(choices=[('menu', 'Menú'), ('view', 'Vista'), ('widget', 'Widget'), ('module', 'Módulo')], max_length=20, verbose_name='Tipo de permiso')),
                ('url_pattern', models.CharField(blank=True, max_length=500, null=True, verbose_name='Patrón URL')),
                ('view_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la vista')),
                ('app_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aplicación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('auto_generated', models.BooleanField(default=True, verbose_name='Auto-generado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso del Sistema',
                'verbose_name_plural': 'Permisos del Sistema',
                'db_table': 'config_system_systempermission',
                'ordering': ['permission_type', 'app_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfilePermissionProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systempermission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_system.systempermissionproxy')),
            ],
            options={
                'db_table': 'config_system_userprofile_permissions',
            },
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ['-nivel_jerarquia', 'nombre'], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='fecha_actualizacion',
            new_name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='configuraciones_ui',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='limite_procesamiento_diario',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='limite_transcripcion_horas',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puede_aprobar_publicacion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puede_configurar_ia',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puede_gestionar_sesiones',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puede_gestionar_usuarios',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puede_procesar_actas',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puede_publicar_actas',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puede_revisar_actas',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puede_transcribir',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='puede_ver_configuraciones',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='ultimo_acceso',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='color',
            field=models.CharField(default='#007bff', help_text='Color en hexadecimal (ej: #007bff)', max_length=7, verbose_name='Color identificativo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='dashboard_personalizado',
            field=models.BooleanField(default=False, help_text='Si tiene un dashboard específico', verbose_name='Dashboard personalizado'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del perfil'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_publico',
            field=models.BooleanField(default=False, help_text='Si puede ser asignado por otros administradores', verbose_name='Perfil público'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_sistema',
            field=models.BooleanField(default=False, help_text='Perfiles creados por el sistema (no editables)', verbose_name='Es del sistema'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_jerarquia',
            field=models.IntegerField(default=0, help_text='0=Usuario común, 1=Supervisor, 2=Administrador, 3=Super Admin', verbose_name='Nivel jerárquico'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Nombre del perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pagina_inicio',
            field=models.CharField(blank=True, help_text='URL de la página inicial tras login', max_length=200, verbose_name='Página de inicio'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='usuarios_asignados',
            field=models.IntegerField(default=0, help_text='Contador de usuarios con este perfil', verbose_name='Usuarios asignados'),
        ),
        migrations.CreateModel(
            name='UserProfileProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del perfil')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permisos incluidos en este perfil', through='config_system.UserProfilePermissionProxy', to='config_system.systempermissionproxy', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'config_system_userprofile',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofilepermissionproxy',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_system.userprofileproxy'),
        ),
        migrations.CreateModel(
            name='PermisoCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del permiso (ej: actas.crear, users.editar)', max_length=100, unique=True, verbose_name='Código del permiso')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del permiso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('categoria', models.CharField(choices=[('actas', 'Gestión de Actas'), ('users', 'Gestión de Usuarios'), ('config', 'Configuración del Sistema'), ('reports', 'Reportes y Estadísticas'), ('files', 'Gestión de Archivos'), ('portal', 'Portal Ciudadano'), ('api', 'API y Integraciones'), ('logs', 'Logs del Sistema'), ('dashboard', 'Dashboard y Métricas'), ('smtp', 'Sistema de Email'), ('ia', 'Inteligencia Artificial'), ('whisper', 'Transcripción de Audio'), ('custom', 'Personalizado')], default='custom', max_length=20, verbose_name='Categoría')),
                ('nivel_acceso', models.CharField(choices=[('leer', 'Solo Lectura'), ('escribir', 'Lectura y Escritura'), ('eliminar', 'Lectura, Escritura y Eliminación'), ('admin', 'Administración Completa')], default='leer', max_length=20, verbose_name='Nivel de acceso')),
                ('urls_permitidas', models.TextField(blank=True, help_text='URLs separadas por comas (ej: /actas/, /actas/crear/)', verbose_name='URLs permitidas')),
                ('mostrar_en_menu', models.BooleanField(default=True, help_text='Si debe aparecer en el menú lateral', verbose_name='Mostrar en menú')),
                ('icono_menu', models.CharField(blank=True, help_text='Clase CSS del icono (ej: fas fa-file-alt)', max_length=50, verbose_name='Icono del menú')),
                ('orden_menu', models.IntegerField(default=100, help_text='Orden de aparición en el menú (menor = primero)', verbose_name='Orden en menú')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_sistema', models.BooleanField(default=False, help_text='Permisos creados por el sistema (no editables)', verbose_name='Es del sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso Personalizado',
                'verbose_name_plural': 'Permisos Personalizados',
                'ordering': ['categoria', 'orden_menu', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuarioLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('editor', 'Editor de Actas'), ('viewer', 'Solo Lectura'), ('secretario', 'Secretario Municipal'), ('alcalde', 'Alcalde'), ('concejal', 'Concejal')], default='viewer', max_length=20, verbose_name='Rol')),
                ('departamento', models.CharField(blank=True, choices=[('secretaria', 'Secretaría Municipal'), ('alcaldia', 'Alcaldía'), ('concejo', 'Concejo Municipal'), ('tesoreria', 'Tesorería'), ('obras', 'Obras Públicas'), ('desarrollo', 'Desarrollo Social'), ('ambiente', 'Medio Ambiente'), ('sistemas', 'Sistemas e IT')], max_length=20, null=True, verbose_name='Departamento')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Extensión')),
                ('puede_configurar_ia', models.BooleanField(default=False, verbose_name='Puede configurar IA')),
                ('puede_ver_configuraciones', models.BooleanField(default=False, verbose_name='Puede ver configuraciones')),
                ('puede_gestionar_usuarios', models.BooleanField(default=False, verbose_name='Puede gestionar usuarios')),
                ('puede_procesar_actas', models.BooleanField(default=False, verbose_name='Puede procesar actas')),
                ('puede_publicar_actas', models.BooleanField(default=False, verbose_name='Puede publicar actas')),
                ('puede_transcribir', models.BooleanField(default=False, verbose_name='Puede transcribir audio')),
                ('puede_revisar_actas', models.BooleanField(default=False, verbose_name='Puede revisar actas')),
                ('puede_aprobar_publicacion', models.BooleanField(default=False, verbose_name='Puede aprobar publicación')),
                ('puede_gestionar_sesiones', models.BooleanField(default=False, verbose_name='Puede gestionar sesiones')),
                ('limite_procesamiento_diario', models.IntegerField(default=10, verbose_name='Límite procesamiento diario')),
                ('limite_transcripcion_horas', models.IntegerField(default=2, verbose_name='Límite transcripción (horas)')),
                ('configuraciones_ui', models.JSONField(blank=True, default=dict, verbose_name='Configuraciones UI')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario Legacy',
                'verbose_name_plural': 'Perfiles de Usuario Legacy',
                'db_table': 'config_system_perfil_usuario_legacy',
            },
        ),
        migrations.CreateModel(
            name='LogPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('acceso_denegado', 'Acceso denegado'), ('permiso_verificado', 'Permiso verificado'), ('perfil_asignado', 'Perfil asignado'), ('perfil_removido', 'Perfil removido'), ('permiso_creado', 'Permiso creado'), ('permiso_modificado', 'Permiso modificado'), ('perfil_creado', 'Perfil creado'), ('perfil_modificado', 'Perfil modificado')], max_length=30)),
                ('url_solicitada', models.CharField(blank=True, max_length=500)),
                ('permiso_codigo', models.CharField(blank=True, max_length=100)),
                ('perfil_nombre', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_permisos', to=settings.AUTH_USER_MODEL)),
                ('usuario_ejecutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Permisos',
                'verbose_name_plural': 'Logs de Permisos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='permisos',
            field=models.ManyToManyField(blank=True, help_text='Permisos que tendrán los usuarios con este perfil', to='config_system.permisocustom', verbose_name='Permisos asignados'),
        ),
        migrations.AlterField(
            model_name='permisosdetallados',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_detallados', to='config_system.perfilusuariolegacy'),
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False, help_text='Si es el perfil principal del usuario', verbose_name='Perfil principal')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha hasta cuando es válida la asignación', null=True, verbose_name='Fecha de expiración')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, verbose_name='Notas de la asignación')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_con_perfil', to='config_system.perfilusuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación Usuario-Perfil',
                'verbose_name_plural': 'Asignaciones Usuario-Perfil',
                'ordering': ['-es_principal', '-fecha_asignacion'],
                'unique_together': {('usuario', 'perfil')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='userprofilepermissionproxy',
            unique_together={('userprofile', 'systempermission')},
        ),
        migrations.CreateModel(
            name='UserProfileAssignmentProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_assignments_made_proxy', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofileassignmentproxy_set', to='config_system.userprofileproxy', verbose_name='Perfil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofileassignmentproxy_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de Perfil',
                'verbose_name_plural': 'Asignaciones de Perfiles',
                'db_table': 'config_system_userprofileassignment',
                'unique_together': {('user', 'profile')},
            },
        ),
    ]
