# Generated by Django 4.2.9 on 2025-09-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripcion', '0001_initial_transcripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontranscripcion',
            name='usar_vad',
            field=models.BooleanField(default=True, help_text='Usar detección de actividad vocal (VAD)'),
        ),
        migrations.AddField(
            model_name='transcripcion',
            name='parametros_personalizados',
            field=models.JSONField(default=dict, help_text='Parámetros personalizados que sobrescriben la configuración base'),
        ),
        migrations.AlterField(
            model_name='configuraciontranscripcion',
            name='modelo_whisper',
            field=models.CharField(choices=[('tiny', 'Tiny (39 MB) - Rápido, menor precisión'), ('base', 'Base (74 MB) - Balanceado'), ('small', 'Small (244 MB) - Buena precisión'), ('medium', 'Medium (769 MB) - Alta precisión'), ('large', 'Large (1550 MB) - Máxima precisión'), ('large-v2', 'Large V2 (1550 MB) - Versión optimizada'), ('large-v3', 'Large V3 (1550 MB) - Última versión')], default='base', help_text='Modelo de Whisper para transcripción', max_length=50),
        ),
    ]
