# Generated by Django 4.2.9 on 2025-09-08 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripcion', '0002_configuraciontranscripcion_usar_vad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontranscripcion',
            name='chunk_duracion',
            field=models.IntegerField(default=30, help_text='Duración de chunks en segundos para procesamiento', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='configuraciontranscripcion',
            name='filtro_ruido',
            field=models.BooleanField(default=True, help_text='Aplicar filtro de reducción de ruido'),
        ),
        migrations.AddField(
            model_name='configuraciontranscripcion',
            name='normalizar_audio',
            field=models.BooleanField(default=True, help_text='Normalizar volumen del audio antes de procesar'),
        ),
        migrations.AddField(
            model_name='configuraciontranscripcion',
            name='overlap_duracion',
            field=models.IntegerField(default=5, help_text='Duración de overlap entre chunks en segundos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='configuraciontranscripcion',
            name='umbral_clustering',
            field=models.FloatField(default=0.7, help_text='Umbral para clustering de hablantes (0.1-1.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='configuraciontranscripcion',
            name='usar_enhanced_diarization',
            field=models.BooleanField(default=True, help_text='Usar características avanzadas de diarización'),
        ),
        migrations.AddField(
            model_name='configuraciontranscripcion',
            name='usar_gpu',
            field=models.BooleanField(default=False, help_text='Usar GPU si está disponible'),
        ),
        migrations.AddField(
            model_name='configuraciontranscripcion',
            name='vad_filtro',
            field=models.FloatField(default=0.5, help_text='Sensibilidad del filtro VAD (0.1-0.9)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.9)]),
        ),
    ]
