# Generated by Django 4.2.9 on 2025-09-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripcion', '0003_configuraciontranscripcion_chunk_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontranscripcion',
            name='vad_filtro',
            field=models.CharField(choices=[('silero', 'Silero (Recomendado)'), ('auditok', 'Auditok')], default='silero', help_text='Tipo de filtro VAD a utilizar', max_length=20),
        ),
    ]
