# Generated by Django 4.2.9 on 2025-09-14 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generador_actas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('backup', 'Backup del Sistema'), ('export_config', 'Exportación de Configuraciones'), ('restart_services', 'Reinicio de Servicios'), ('preview_template', 'Vista Previa de Plantilla'), ('export_template', 'Exportación de Plantilla'), ('reset_config', 'Reset de Configuraciones'), ('test_providers', 'Prueba de Proveedores IA'), ('duplicate_segment', 'Duplicar Segmento'), ('duplicate_template', 'Duplicar Plantilla')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('progreso', models.IntegerField(default=0, help_text='Progreso en porcentaje (0-100)')),
                ('mensaje_estado', models.TextField(blank=True, help_text='Mensaje descriptivo del estado actual')),
                ('parametros_entrada', models.JSONField(default=dict, help_text='Parámetros de entrada de la operación')),
                ('resultado', models.JSONField(blank=True, default=dict, help_text='Resultado de la operación')),
                ('logs', models.JSONField(default=list, help_text='Logs detallados de la operación')),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to='operaciones_sistema/')),
                ('url_descarga', models.URLField(blank=True, help_text='URL de descarga del resultado')),
                ('task_id', models.CharField(blank=True, help_text='ID de la tarea Celery', max_length=255)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('tiempo_ejecucion', models.DurationField(blank=True, null=True)),
                ('expira_en', models.DateTimeField(blank=True, help_text='Fecha de expiración del resultado', null=True)),
                ('notificar_usuario', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('mensaje', models.TextField()),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_detallados', to='generador_actas.operacionsistema')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Clave única de configuración', max_length=100, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('valor', models.JSONField(help_text='Valor de la configuración')),
                ('valor_por_defecto', models.JSONField(help_text='Valor por defecto')),
                ('tipo_dato', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número entero'), ('float', 'Número decimal'), ('boolean', 'Verdadero/Falso'), ('json', 'JSON'), ('list', 'Lista')], default='string', max_length=50)),
                ('validacion', models.JSONField(blank=True, default=dict, help_text='Reglas de validación')),
                ('es_requerido', models.BooleanField(default=False)),
                ('es_publico', models.BooleanField(default=False, help_text='Si es visible en APIs públicas')),
                ('version', models.IntegerField(default=1)),
                ('historial_valores', models.JSONField(default=list, help_text='Historial de cambios de valor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['clave'],
            },
        ),
        migrations.AddIndex(
            model_name='operacionsistema',
            index=models.Index(fields=['usuario', '-fecha_inicio'], name='generador_a_usuario_562b13_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionsistema',
            index=models.Index(fields=['tipo', 'estado'], name='generador_a_tipo_dc2574_idx'),
        ),
        migrations.AddIndex(
            model_name='operacionsistema',
            index=models.Index(fields=['task_id'], name='generador_a_task_id_b027e4_idx'),
        ),
        migrations.AddIndex(
            model_name='logoperacion',
            index=models.Index(fields=['operacion', '-timestamp'], name='generador_a_operaci_87116c_idx'),
        ),
        migrations.AddIndex(
            model_name='logoperacion',
            index=models.Index(fields=['nivel'], name='generador_a_nivel_8ec9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionsistema',
            index=models.Index(fields=['clave'], name='generador_a_clave_849c34_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionsistema',
            index=models.Index(fields=['es_publico'], name='generador_a_es_publ_31ea1e_idx'),
        ),
    ]
