# Generated by Django 4.2.9 on 2025-09-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_actas', '0002_operacionsistema_logoperacion_configuracionsistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedoria',
            name='prompt_sistema_global',
            field=models.TextField(blank=True, help_text='Prompt de sistema global para este proveedor'),
        ),
        migrations.AddField(
            model_name='proveedoria',
            name='total_llamadas',
            field=models.IntegerField(default=0, help_text='Total de llamadas realizadas'),
        ),
        migrations.AddField(
            model_name='proveedoria',
            name='total_tokens_usados',
            field=models.BigIntegerField(default=0, help_text='Total de tokens consumidos'),
        ),
        migrations.AddField(
            model_name='proveedoria',
            name='ultima_conexion_exitosa',
            field=models.DateTimeField(blank=True, help_text='Última conexión exitosa', null=True),
        ),
        migrations.AddField(
            model_name='proveedoria',
            name='ultimo_error',
            field=models.TextField(blank=True, help_text='Último error registrado'),
        ),
        migrations.AlterField(
            model_name='proveedoria',
            name='api_url',
            field=models.URLField(blank=True, help_text='URL base de la API'),
        ),
        migrations.AlterField(
            model_name='proveedoria',
            name='modelo',
            field=models.CharField(help_text='Modelo específico a usar', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedoria',
            name='tipo',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini'), ('ollama', 'Ollama (Local)'), ('lmstudio', 'LM Studio (Local)'), ('groq', 'Groq'), ('generic1', 'Proveedor Genérico 1'), ('generic2', 'Proveedor Genérico 2')], help_text='Tipo de proveedor de IA', max_length=50),
        ),
    ]
