# Generated by Django 4.2.9 on 2025-09-15 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generador_actas', '0003_proveedoria_prompt_sistema_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentoplantilla',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está disponible para uso'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='proveedor_ia',
            field=models.ForeignKey(blank=True, help_text='Proveedor IA para procesamiento (solo segmentos dinámicos)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='generador_actas.proveedoria'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='tiempo_promedio_procesamiento',
            field=models.FloatField(default=0.0, help_text='Tiempo promedio de procesamiento en segundos'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='total_usos',
            field=models.IntegerField(default=0, help_text='Total de veces que se ha usado'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='ultima_prueba',
            field=models.DateTimeField(blank=True, help_text='Última vez que se probó', null=True),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='ultimo_resultado_prueba',
            field=models.TextField(blank=True, help_text='Resultado de la última prueba'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='variables_personalizadas',
            field=models.JSONField(blank=True, default=dict, help_text='Variables JSON personalizables (fecha, participantes, etc.)'),
        ),
    ]
