# Generated by Django 4.2.9 on 2025-09-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador_actas', '0004_segmentoplantilla_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentoplantilla',
            name='componentes',
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='contenido_estatico',
            field=models.TextField(blank=True, help_text='Contenido fijo para segmentos estáticos (admite variables {{variable}})'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='contexto_requerido',
            field=models.JSONField(blank=True, default=list, help_text='Elementos de contexto requeridos (transcripcion, participantes, etc)'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='formato_salida',
            field=models.CharField(choices=[('texto', 'Texto plano'), ('html', 'HTML estructurado'), ('markdown', 'Markdown'), ('json', 'JSON estructurado'), ('tabla', 'Tabla/Lista'), ('personalizado', 'Formato personalizado')], default='texto', help_text='Formato de salida del contenido', max_length=20),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='formato_validacion',
            field=models.CharField(blank=True, help_text='Patrón regex o formato específico', max_length=50),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='longitud_maxima',
            field=models.IntegerField(blank=True, help_text='Longitud máxima del resultado en caracteres', null=True),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='prompt_sistema',
            field=models.TextField(blank=True, help_text='Prompt de sistema específico (opcional, override del proveedor)'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='reintentos_ia',
            field=models.IntegerField(default=2, help_text='Número de reintentos en caso de error'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='tasa_exito',
            field=models.FloatField(default=0.0, help_text='Porcentaje de procesamientos exitosos (0-100)'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='tiempo_limite_ia',
            field=models.IntegerField(default=60, help_text='Tiempo límite para procesamiento IA (segundos)'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='total_errores',
            field=models.IntegerField(default=0, help_text='Total de errores en procesamiento'),
        ),
        migrations.AddField(
            model_name='segmentoplantilla',
            name='validaciones_salida',
            field=models.JSONField(blank=True, default=list, help_text='Validaciones a aplicar en la salida'),
        ),
        migrations.AlterField(
            model_name='segmentoplantilla',
            name='categoria',
            field=models.CharField(choices=[('encabezado', 'Encabezado'), ('titulo', 'Título'), ('fecha_hora', 'Fecha y Hora'), ('participantes', 'Participantes/Asistencia'), ('orden_dia', 'Orden del Día'), ('introduccion', 'Introducción'), ('desarrollo', 'Desarrollo/Contenido'), ('transcripcion', 'Transcripción'), ('resumen', 'Resumen Ejecutivo'), ('acuerdos', 'Acuerdos/Resoluciones'), ('compromisos', 'Compromisos/Tareas'), ('seguimiento', 'Seguimiento'), ('cierre', 'Cierre'), ('firmas', 'Firmas/Validaciones'), ('anexos', 'Anexos/Documentos'), ('legal', 'Marco Legal'), ('otros', 'Otros')], help_text='Categoría del segmento', max_length=50),
        ),
        migrations.AlterField(
            model_name='segmentoplantilla',
            name='codigo',
            field=models.CharField(help_text='Código único del segmento (ej: TITULO_ACTA)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='segmentoplantilla',
            name='descripcion',
            field=models.TextField(help_text='Descripción del propósito y funcionamiento del segmento'),
        ),
        migrations.AlterField(
            model_name='segmentoplantilla',
            name='estructura_json',
            field=models.JSONField(blank=True, default=dict, help_text='Estructura esperada del resultado JSON'),
        ),
        migrations.AlterField(
            model_name='segmentoplantilla',
            name='parametros_entrada',
            field=models.JSONField(blank=True, default=list, help_text='Lista de parámetros requeridos del contexto'),
        ),
        migrations.AlterField(
            model_name='segmentoplantilla',
            name='prompt_ia',
            field=models.TextField(blank=True, help_text='Prompt para segmentos dinámicos procesados con IA'),
        ),
        migrations.AlterField(
            model_name='segmentoplantilla',
            name='tiempo_promedio_procesamiento',
            field=models.FloatField(default=0.0, help_text='Tiempo promedio de procesamiento (segundos)'),
        ),
        migrations.AlterField(
            model_name='segmentoplantilla',
            name='tipo',
            field=models.CharField(choices=[('estatico', 'Estático - Contenido fijo'), ('dinamico', 'Dinámico - Procesado con IA'), ('hibrido', 'Híbrido - Estático + IA opcional')], help_text='Tipo de procesamiento', max_length=20),
        ),
        migrations.AlterField(
            model_name='segmentoplantilla',
            name='variables_personalizadas',
            field=models.JSONField(blank=True, default=dict, help_text='Variables JSON personalizables por el usuario'),
        ),
        migrations.AddIndex(
            model_name='segmentoplantilla',
            index=models.Index(fields=['categoria', 'activo'], name='generador_a_categor_ea4bad_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentoplantilla',
            index=models.Index(fields=['tipo', 'activo'], name='generador_a_tipo_0be875_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentoplantilla',
            index=models.Index(fields=['codigo'], name='generador_a_codigo_ab4eea_idx'),
        ),
    ]
