# Generated by Django 4.2.9 on 2025-09-28 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0004_procesamientoaudio_bit_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generador_actas', '0005_remove_segmentoplantilla_componentes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionPlantilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la ejecución', max_length=200)),
                ('variables_contexto', models.JSONField(blank=True, default=dict, help_text='Variables específicas para esta ejecución')),
                ('configuracion_overrides', models.JSONField(blank=True, default=dict, help_text='Sobrescribir configuración por segmento')),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('procesando_segmentos', 'Procesando Segmentos'), ('editando_resultados', 'Editando Resultados'), ('unificando', 'Unificando Acta'), ('completada', 'Completada'), ('error', 'Error'), ('cancelada', 'Cancelada')], default='iniciada', max_length=50)),
                ('progreso_actual', models.IntegerField(default=0, help_text='Segmentos procesados')),
                ('progreso_total', models.IntegerField(default=0, help_text='Total de segmentos')),
                ('tiempo_inicio', models.DateTimeField(auto_now_add=True)),
                ('tiempo_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_total_segundos', models.IntegerField(blank=True, null=True)),
                ('resultados_parciales', models.JSONField(blank=True, default=dict, help_text='Resumen de resultados por segmento')),
                ('errores', models.JSONField(blank=True, default=list, help_text='Errores encontrados')),
                ('logs_procesamiento', models.TextField(blank=True, help_text='Logs detallados del proceso')),
                ('prompt_unificacion_override', models.TextField(blank=True, help_text='Override del prompt de unificación')),
                ('resultado_unificacion', models.TextField(blank=True, help_text='Acta unificada generada')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='generador_actas.plantillaacta')),
                ('proveedor_ia_global', models.ForeignKey(help_text='IA utilizada para todos los segmentos', on_delete=django.db.models.deletion.PROTECT, to='generador_actas.proveedoria')),
                ('transcripcion', models.ForeignKey(blank=True, help_text='Transcripción utilizada como fuente', null=True, on_delete=django.db.models.deletion.CASCADE, to='audio_processing.procesamientoaudio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones_plantillas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de Plantilla',
                'verbose_name_plural': 'Ejecuciones de Plantillas',
                'ordering': ['-tiempo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ActaBorrador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título del acta generada', max_length=300)),
                ('numero_acta', models.CharField(blank=True, help_text='Número oficial del acta', max_length=50)),
                ('contenido_html', models.TextField(help_text='Contenido del acta en HTML')),
                ('contenido_markdown', models.TextField(blank=True, help_text='Versión Markdown del acta')),
                ('resumen_ejecutivo', models.TextField(blank=True, help_text='Resumen ejecutivo del acta')),
                ('fecha_acta', models.DateField(help_text='Fecha oficial del acta')),
                ('lugar_sesion', models.CharField(blank=True, help_text='Lugar donde se realizó la sesión', max_length=200)),
                ('participantes', models.JSONField(blank=True, default=list, help_text='Lista de participantes')),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('borrador', 'Borrador'), ('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('formato_preferido', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('docx', 'Word Document'), ('pdf', 'PDF')], default='html', max_length=20)),
                ('configuracion_formato', models.JSONField(blank=True, default=dict, help_text='Configuración específica de formato')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='actas/pdf/')),
                ('archivo_docx', models.FileField(blank=True, null=True, upload_to='actas/docx/')),
                ('calidad_estimada', models.FloatField(blank=True, help_text='Calidad estimada del acta (0-1)', null=True)),
                ('tiempo_generacion_segundos', models.IntegerField(blank=True, null=True)),
                ('comentarios_revision', models.TextField(blank=True, help_text='Comentarios de revisión')),
                ('historial_cambios', models.JSONField(blank=True, default=list, help_text='Historial de cambios')),
                ('ejecucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_borrador', to='generador_actas.ejecucionplantilla')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_borradores_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_ultima_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_borradores_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acta Borrador',
                'verbose_name_plural': 'Actas Borrador',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_procesamiento', models.IntegerField(help_text='Orden en que se procesó')),
                ('prompt_usado', models.TextField(help_text='Prompt final enviado a la IA')),
                ('configuracion_ia', models.JSONField(blank=True, default=dict, help_text='Parámetros IA utilizados')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('editado', 'Editado Manualmente'), ('error', 'Error'), ('omitido', 'Omitido')], default='pendiente', max_length=50)),
                ('resultado_crudo', models.TextField(blank=True, help_text='Respuesta cruda de la IA')),
                ('resultado_procesado', models.TextField(blank=True, help_text='Resultado limpio y procesado')),
                ('resultado_editado', models.TextField(blank=True, help_text='Versión editada manualmente')),
                ('tiempo_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('tiempo_total_ms', models.IntegerField(blank=True, help_text='Tiempo de procesamiento en ms', null=True)),
                ('tokens_utilizados', models.IntegerField(blank=True, help_text='Tokens consumidos', null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('version_resultado', models.IntegerField(default=1, help_text='Versión del resultado')),
                ('fecha_ultima_edicion', models.DateTimeField(auto_now=True)),
                ('metadatos_ia', models.JSONField(blank=True, default=dict, help_text='Metadatos de respuesta IA')),
                ('notas_edicion', models.TextField(blank=True, help_text='Notas del usuario sobre ediciones')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='generador_actas.ejecucionplantilla')),
                ('proveedor_ia_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='generador_actas.proveedoria')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generador_actas.segmentoplantilla')),
                ('usuario_ultima_edicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de Segmento',
                'verbose_name_plural': 'Resultados de Segmentos',
                'ordering': ['ejecucion', 'orden_procesamiento'],
                'indexes': [models.Index(fields=['ejecucion', 'orden_procesamiento'], name='generador_a_ejecuci_8bb7e0_idx'), models.Index(fields=['estado'], name='generador_a_estado_1c5c6c_idx'), models.Index(fields=['segmento'], name='generador_a_segment_a40f2b_idx')],
                'unique_together': {('ejecucion', 'segmento')},
            },
        ),
        migrations.AddIndex(
            model_name='ejecucionplantilla',
            index=models.Index(fields=['estado', '-tiempo_inicio'], name='generador_a_estado_87e7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ejecucionplantilla',
            index=models.Index(fields=['usuario', '-tiempo_inicio'], name='generador_a_usuario_b284d2_idx'),
        ),
        migrations.AddIndex(
            model_name='ejecucionplantilla',
            index=models.Index(fields=['plantilla', '-tiempo_inicio'], name='generador_a_plantil_4b8bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='actaborrador',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='generador_a_estado_65add9_idx'),
        ),
        migrations.AddIndex(
            model_name='actaborrador',
            index=models.Index(fields=['usuario_creacion', '-fecha_creacion'], name='generador_a_usuario_b528b2_idx'),
        ),
        migrations.AddIndex(
            model_name='actaborrador',
            index=models.Index(fields=['fecha_acta'], name='generador_a_fecha_a_372a06_idx'),
        ),
    ]
