# Generated by Django 4.2.9 on 2025-09-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generador_actas', '0006_ejecucionplantilla_actaborrador_resultadosegmento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('segmento', 'Procesamiento de Segmento'), ('final', 'Procesamiento Final/Global'), ('unificacion', 'Unificación General')], help_text='Tipo de procesamiento', max_length=20)),
                ('segmento_nombre', models.CharField(blank=True, help_text='Nombre del segmento (solo para tipo segmento)', max_length=100)),
                ('prompt_completo', models.TextField(help_text='Prompt completo enviado a la IA')),
                ('longitud_prompt', models.IntegerField(help_text='Longitud del prompt en caracteres')),
                ('hash_prompt', models.CharField(help_text='Hash MD5 del prompt para deduplicación', max_length=64)),
                ('respuesta_ia', models.TextField(blank=True, help_text='Respuesta completa de la IA')),
                ('longitud_respuesta', models.IntegerField(default=0, help_text='Longitud de la respuesta')),
                ('tokens_estimados', models.IntegerField(default=0, help_text='Tokens estimados usados')),
                ('proveedor_ia', models.CharField(help_text='Proveedor IA usado', max_length=50)),
                ('modelo_usado', models.CharField(blank=True, help_text='Modelo específico usado', max_length=50)),
                ('tiempo_procesamiento', models.FloatField(default=0, help_text='Tiempo de procesamiento en segundos')),
                ('exitoso', models.BooleanField(default=True, help_text='Si el procesamiento fue exitoso')),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si falló')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acta', models.ForeignKey(help_text='Acta asociada al prompt', on_delete=django.db.models.deletion.CASCADE, related_name='prompts_log', to='generador_actas.actagenerada')),
            ],
            options={
                'verbose_name': 'Log de Prompt',
                'verbose_name_plural': 'Logs de Prompts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['acta', 'tipo'], name='generador_a_acta_id_81a2ba_idx'), models.Index(fields=['timestamp'], name='generador_a_timesta_aa0a33_idx'), models.Index(fields=['hash_prompt'], name='generador_a_hash_pr_91bfa0_idx')],
            },
        ),
    ]
