# Generated by Django 4.2.9 on 2025-09-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generador_actas', '0007_promptlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromptLog',
        ),
    ]
