# Generated by Django 4.2.9 on 2025-09-06 16:50

import apps.pages.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del acta', max_length=200)),
                ('numero_acta', models.CharField(help_text='Número único del acta', max_length=50, unique=True)),
                ('numero_sesion', models.CharField(help_text='Número de la sesión', max_length=50)),
                ('fecha_sesion', models.DateTimeField(help_text='Fecha y hora de la sesión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('resumen', models.TextField(help_text='Resumen ejecutivo del acta')),
                ('contenido', models.TextField(blank=True, help_text='Contenido completo del acta')),
                ('orden_del_dia', models.TextField(blank=True, help_text='Orden del día de la sesión')),
                ('acuerdos', models.TextField(blank=True, help_text='Acuerdos tomados en la sesión')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Archivo PDF del acta', null=True, upload_to=apps.pages.models.acta_upload_path)),
                ('imagen_preview', models.ImageField(blank=True, help_text='Imagen de vista previa del acta', null=True, upload_to=apps.pages.models.acta_image_upload_path)),
                ('acceso', models.CharField(choices=[('publico', 'Acceso Público'), ('restringido', 'Acceso Restringido'), ('confidencial', 'Confidencial')], default='publico', help_text='Nivel de acceso al documento', max_length=15)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('presidente', models.CharField(help_text='Presidente de la sesión', max_length=100)),
                ('asistentes', models.TextField(blank=True, help_text='Lista de asistentes')),
                ('ausentes', models.TextField(blank=True, help_text='Lista de ausentes')),
                ('transcripcion_ia', models.BooleanField(default=False, help_text='¿Fue transcrita por IA?')),
                ('precision_ia', models.DecimalField(blank=True, decimal_places=2, help_text='Precisión de la transcripción IA (%)', max_digits=5, null=True)),
                ('tiempo_procesamiento', models.DurationField(blank=True, null=True)),
                ('palabras_clave', models.CharField(blank=True, help_text='Palabras clave separadas por comas', max_length=500)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acta Municipal',
                'verbose_name_plural': 'Actas Municipales',
                'ordering': ['-fecha_sesion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('borrador', 'Borrador'), ('transcripcion', 'En Transcripción'), ('revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de Acta',
                'verbose_name_plural': 'Estados de Actas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ordinaria', 'Sesión Ordinaria'), ('extraordinaria', 'Sesión Extraordinaria'), ('solemne', 'Sesión Solemne'), ('publica', 'Audiencia Pública'), ('comision', 'Comisión')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', help_text='Color en formato hexadecimal', max_length=7)),
                ('icono', models.CharField(default='fas fa-file-alt', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Sesión',
                'verbose_name_plural': 'Tipos de Sesiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VisualizacionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_visualizacion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_lectura', models.DurationField(blank=True, null=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones', to='pages.actamunicipal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualización de Acta',
                'verbose_name_plural': 'Visualizaciones de Actas',
                'ordering': ['-fecha_visualizacion'],
            },
        ),
        migrations.CreateModel(
            name='DescargaActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='pages.actamunicipal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarga de Acta',
                'verbose_name_plural': 'Descargas de Actas',
                'ordering': ['-fecha_descarga'],
            },
        ),
        migrations.AddField(
            model_name='actamunicipal',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.estadoacta'),
        ),
        migrations.AddField(
            model_name='actamunicipal',
            name='secretario',
            field=models.ForeignKey(help_text='Secretario responsable del acta', on_delete=django.db.models.deletion.PROTECT, related_name='actas_como_secretario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actamunicipal',
            name='tipo_sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.tiposesion'),
        ),
        migrations.AddIndex(
            model_name='actamunicipal',
            index=models.Index(fields=['numero_acta'], name='pages_actam_numero__91d985_idx'),
        ),
        migrations.AddIndex(
            model_name='actamunicipal',
            index=models.Index(fields=['fecha_sesion'], name='pages_actam_fecha_s_35b029_idx'),
        ),
        migrations.AddIndex(
            model_name='actamunicipal',
            index=models.Index(fields=['estado'], name='pages_actam_estado__ba0d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='actamunicipal',
            index=models.Index(fields=['acceso'], name='pages_actam_acceso_3d8b07_idx'),
        ),
        migrations.AddIndex(
            model_name='actamunicipal',
            index=models.Index(fields=['tipo_sesion'], name='pages_actam_tipo_se_21b198_idx'),
        ),
    ]
