# Generated by Django 4.2.9 on 2025-09-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_actamunicipal_estadoacta_tiposesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('poblacion', 'Población'), ('economia', 'Economía'), ('servicios', 'Servicios Públicos'), ('infraestructura', 'Infraestructura'), ('medio_ambiente', 'Medio Ambiente'), ('social', 'Desarrollo Social'), ('gobierno', 'Gestión Gubernamental')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unidad', models.CharField(help_text='Ej: habitantes, pesos, metros, %', max_length=50)),
                ('fecha', models.DateField()),
                ('fuente', models.CharField(help_text='Fuente de la información', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='fas fa-chart-bar', max_length=50)),
                ('color', models.CharField(default='#28a745', max_length=7)),
            ],
            options={
                'verbose_name': 'Estadística Municipal',
                'verbose_name_plural': 'Estadísticas Municipales',
                'ordering': ['-fecha', 'categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('participacion', 'Participación Ciudadana'), ('tiempo_respuesta', 'Tiempo de Respuesta'), ('publicacion', 'Publicación de Información'), ('cumplimiento', 'Cumplimiento Legal'), ('accesibilidad', 'Accesibilidad'), ('calidad', 'Calidad de la Información')], max_length=20)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje (%)'), ('numero', 'Número'), ('tiempo', 'Tiempo (días/horas)'), ('puntuacion', 'Puntuación (1-10)')], max_length=15)),
                ('icono', models.CharField(default='fas fa-chart-line', max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Indicador de Transparencia',
                'verbose_name_plural': 'Indicadores de Transparencia',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('infraestructura', 'Infraestructura'), ('servicios', 'Servicios Públicos'), ('social', 'Desarrollo Social'), ('cultura', 'Cultura y Recreación'), ('medio_ambiente', 'Medio Ambiente'), ('seguridad', 'Seguridad'), ('economia', 'Desarrollo Económico')], max_length=20)),
                ('estado', models.CharField(choices=[('planificacion', 'En Planificación'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En Ejecución'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], max_length=15)),
                ('presupuesto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presupuesto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('responsable', models.CharField(max_length=100)),
                ('contratista', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('beneficiarios_estimados', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Proyecto Municipal',
                'verbose_name_plural': 'Proyectos Municipales',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetricaTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('mes', models.PositiveIntegerField()),
                ('año', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='pages.indicadortransparencia')),
            ],
            options={
                'verbose_name': 'Métrica de Transparencia',
                'verbose_name_plural': 'Métricas de Transparencia',
                'ordering': ['-año', '-mes', '-fecha'],
                'unique_together': {('indicador', 'fecha')},
            },
        ),
    ]
