# Generated by Django 4.2.9 on 2025-09-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_eventomunicipal_documentoevento_asistenciaevento_and_more'),
    ]

    operations = [
    ]
