# Generated by Django 4.2.9 on 2025-09-06 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_auto_20250906_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoevento',
            options={'ordering': ['orden', '-fecha_subida'], 'verbose_name': 'Documento de Evento', 'verbose_name_plural': 'Documentos de Eventos'},
        ),
        migrations.AddField(
            model_name='documentoevento',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='documentoevento',
            name='tipo_documento',
            field=models.CharField(choices=[('agenda', 'Agenda'), ('acta', 'Acta'), ('presentacion', 'Presentación'), ('anexo', 'Anexo'), ('convocatoria', 'Convocatoria'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='eventomunicipal',
            name='invitados_externos',
            field=models.TextField(blank=True, help_text='Emails de invitados externos separados por comas'),
        ),
        migrations.AlterField(
            model_name='eventomunicipal',
            name='asistentes_invitados',
            field=models.ManyToManyField(blank=True, help_text='Usuarios registrados invitados al evento', related_name='eventos_invitado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvitacionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('mensaje_personalizado', models.TextField(blank=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('vista', 'Vista'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='enviada', max_length=15)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_externas', to='pages.eventomunicipal')),
            ],
            options={
                'verbose_name': 'Invitación Externa',
                'verbose_name_plural': 'Invitaciones Externas',
                'ordering': ['-fecha_envio'],
                'unique_together': {('evento', 'email')},
            },
        ),
    ]
