# Generated by Django 4.2.9 on 2025-09-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_documentoevento_options_documentoevento_orden_and_more'),
    ]

    operations = [
    ]
