# Generated by Django 4.2.9 on 2025-09-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20250906_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='descargaacta',
            name='formato',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Texto Plano'), ('word', 'Word Document')], default='pdf', max_length=10),
        ),
    ]
