# Generated by Django 4.2.9 on 2025-09-28 18:28

import apps.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_descargaacta_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='actamunicipal',
            name='archivo_txt',
            field=models.FileField(blank=True, help_text='Archivo TXT del acta', null=True, upload_to=apps.pages.models.acta_upload_path),
        ),
        migrations.AddField(
            model_name='actamunicipal',
            name='archivo_word',
            field=models.FileField(blank=True, help_text='Archivo Word del acta', null=True, upload_to=apps.pages.models.acta_upload_path),
        ),
    ]
